trigger:
- main

pool:
  name: default

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Build Frontend'

  - script: |
      cd backend
      npm install
      npm run build
    displayName: 'Build Backend'
