version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27018:27017"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile  # Explicitly mention Dockerfile if it's named Dockerfile or adjust if needed
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Explicitly mention Dockerfile if it's named Dockerfile or adjust if needed
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.sample
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  logs:
